# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: dev
      PGPASSWORD: dev123
      PGDATABASE: smart_bank_dev
      PGPORT: 5432
      # Hostname of our Postgres container


# Define the volumes
volumes:
  pgdata:
